- libxlsxwriter.podspec
Adds a Podspec file for CocoaPods (https://cocoapods.org) to simplify the integration of the library in iOS projects.
> Add Podspec

- include/xlsxwriter/worksheet.h
- src/worksheet.c
This change brings red-black trees to the cells (columns). It improves performance in cases where there are many columns that aren't accessed in sequential order.
> Convert cell data structure from TAILQ to RB tree

- include/xlsxwriter/shared_strings.h
- src/shared_strings.c
Resubmit on dev branch. This speeds up performance of there shared string table with many shared strings.
> Convert shared string table from hash to RB tree.

- cocoapods/libxlsxwriter-umbrella.h
- cocoapods/libxlsxwriter.modulemap
- libxlsxwriter.podspec
With the final version of CocoaPods 1.0.0 out, I made another attempt and was able to add support for `use_frameworks!` without the need for introducing an additional subspec. I now recommend merging this PR over my previous one. However, I’m leaving the old PR open as well until the whole discussion on this topic is closed.
I started out as in the previous PR (#44), thus since a straight build of the current pod with `use_frameworks!` leads to:
I added
```ruby
s.pod_target_xcconfig   = { 'USER_HEADER_SEARCH_PATHS' => '${PODS_ROOT}/libxlsxwriter/include’ }
```
in the podspec.
Then a new problem arose:
In my previous PR, I solved this error by moving the `xlsxwriter.h` header inside of the `xlsxwriter` directory. However, what **I had missed out** is that it is possible to [specify a …
> Add ability to build pod as a framework

- docs/src/faq.dox
- docs/src/introduction.dox
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- .drone.yml
- CMakeLists.txt
- appveyor.yml
- test/unit/ctest.h
Hi @jmcnamara, this PR fixes 3 issues we've previously discussed, and adds continual integration for MSYS2 (one that we had not discussed). It's broken into 3 commits accordingly.
1. Fixes [issue 108](https://github.com/jmcnamara/libxlsxwriter/issues/108) so the CMake generation properly includes iowin32.c.
2. Fixes [issue 107](https://github.com/jmcnamara/libxlsxwriter/issues/107) to make unittests work on MSVC.
3. Adds continual integration for AppVeyor (Visual Studio 2015 and Visual Studio 2017) and [Tea-CI](https://tea-ci.org/Alexhuszagh/libxlsxwriter) (MSYS2).
Combined, this should be good assurance that the CMake builds work on a large variety of platforms, in addition to the Makefile builds, which is especially useful for Visual Studio.
I also need to submit a PR for an example for …
> Fixes 3 Issues

- CMakeLists.txt
Patch for issues discovered in #115, as well as a patch to remove numerous superfluous errors by MSVC by setting the `_CRT_SECURE_NO_WARNINGS` flag (MSVC warns for functions that may lead to a buffer overflow, but warns for functions `fread` and `snprintf`, which already require you to provide to length of the destination buffer, so the CRT warnings are effectively useless IMO, especially when you require the use of standard C/POSIX functions).
> MSVC and Shared Linkage Bug Fixes

- .drone.yml
- CMakeLists.txt
- appveyor.yml
Fixes:
- Missing DLL installation on Windows
- Missing exported symbols on MSVC when creating a DLL.
- Increases the number of configurations for MinGW and MSVC CI to ensure static/shared builds, with more platforms and build types.
> Patch for #115 and Patches for MSVC Shared Builds

- CMakeLists.txt
- First commit fixes #131, which simplifies linking to xlsxwriter with multiple dependencies
- Second commit fixes #119, by adding the `USE_SYSTEM_MINIZIP` flag, which by default is off but can be specified during CMake configuration using `-DUSE_SYSTEM_MINIZIP=ON`.
> Add system minizip support to CMakeLists

- cmake/FindMINIZIP.cmake
Very sorry, forgot to include a module in my PR. This is required to find the system minizip installation.
During configuration, you can call `find_package(MINIZIP)` to locate the includes and libraries for minizip, since CMake does not bundle support for minizip internally.
> Forgot to include 'FindMINIZIP' module to find system minizip

- src/packager.c
Patch to fix issue #153. As my Windows development machine is currently down, I cannot comprehensively test it, but it's been testing using cross-compilation on Fedora MinGW without issues.
Steps. to confirm it works (cross-compiling):
1. `git clone https://github.com/Alexhuszagh/libxlsxwriter && cd libxlsxwriter`
2. `mkdir build && cd build`
3. `wget https://github.com/madler/zlib/archive/v1.2.11.zip`
4. `unzip v1.2.11.zip`
5. `cd zlib-1.2.11`
6. `cmake . # -DCMAKE_C_FLAGS="-D_UNICODE"`
7. `cd ..`
8. `cmake .. -DBUILD_TESTS=ON -DZLIB_INCLUDE_DIR=zlib-1.2.11 -DZLIB_LIBRARY=zlib-1.2.11/libzlibstatic.a # -DCMAKE_C_FLAGS="-D_UNICODE"`
I've tried all 4 forms of the `_UNICODE` combinations cross-compiling, so it should work.
Thoughts @RalfKubis, @jmcnamara?
> Fix for Issue #153

- CMakeLists.txt
I'm not 100% sure  of minimal version required, but at least 3.0 is ok (and raised to 3.1 by pr #168)
> Fix #166 use GNUInstallDirs cmake module

- CMakeLists.txt
I tracked down the origin of the code for the PDB renaming, since it retrospect it seemed suspect to me. It was part of the following [commit](https://github.com/jmcnamara/libxlsxwriter/commit/9a78c323a925c75d8feffb7c3f6a7773e79d2628#diff-af3b638bc2a3e6c650974192a53c7291), which added various hardcoded values for certain common use cases we've had to subsequently remove for good reason.
The more I looked at the code, the more I realized that re-writing the PDB (symbol info) for a specific build to a global project directory is a bad idea, and that was should be only installing from the project-specific PDB anyway.
Hence, the changes. I'll be careful to review code more carefully before signing off on it in the future. This fixes #175.
> Fix for spurious PDB renaming.

- include/xlsxwriter/utility.h
- src/utility.c
May be useful to check build time version (LXW_VERSION) against runtime version, and to display information in some debug part.
> add lxw_version function to rerieve runtime library version

- Makefile
This came up whilst packaging for pkgsrc which adds a Python version
suffix to binaries.
Relates to #205.
> Make py.test name configurable

- include/xlsxwriter/app.h
- include/xlsxwriter/chartsheet.h
- include/xlsxwriter/content_types.h
- include/xlsxwriter/core.h
- include/xlsxwriter/custom.h
- include/xlsxwriter/drawing.h
- include/xlsxwriter/format.h
- include/xlsxwriter/relationships.h
- include/xlsxwriter/shared_strings.h
- include/xlsxwriter/styles.h
- include/xlsxwriter/theme.h
- src/app.c
- src/content_types.c
- src/core.c
- src/custom.c
- src/drawing.c
- src/format.c
- src/relationships.c
- src/shared_strings.c
- src/styles.c
- src/theme.c
- test/unit/chartsheet/test_chartsheet.c
The C standard (and `-Wstrict-prototypes`) requires that functions which take no arguments be declared as foobar(void) instead of foobar().
> Fix compile-time warnings with strict prototypes enabled. Fixes #208

- src/Makefile
So the lib directory and such can be overridden in/by the build
environment.
> Respect LDFLAGS when linking

- CMakeLists.txt
This should patch issue #243, and potentially #242. 
I've tested the following code produces no warnings, and respects the `ZLIB_ROOT` variable on the following CMake versions (on Linux, x86-64):
- 3.14.5
- 3.12.0
- 3.11.4 (The last release prior to 3.12.0)
- 3.9.2 (An arbitrary older release)
> Patch for issue #243, by specifying the new policy for <PackageName>_ROOT.

- CMakeLists.txt
On non-UTF-8 locales(GBK, for example), those CJK characters in `theme.c` cause build errors:
```
src\theme.c(38): error C2059: syntax error: '>'
src\theme.c(38): error C2001: newline in constant
src\theme.c(72): error C2001: newline in constant
```
This patch also removes unknown option `/O0`. GCC's `-O0` equivalent should be `/Ot`(https://github.com/swig/cccl/blob/master/cccl). Do you mean `/Od`(the default) here?
> CMake: Add /utf-8 MSVC compiler option for non-UTF-8 locales

- Makefile
- docs/src/getting_started.dox
- src/Makefile
`PREFIX` is the final location on the user's system. `DESTDIR` could
be staging directory for a package build, a chroot, etc. The
distinction is important because you don't want `DESTDIR` to end up
in paths compiled into the program, e.g. the location of a helpfile
or library.
(Applies only to the makefiles, not CMake)
Also use `PREFIX` for `-install_name`.
Resolves #216
Succeeds #209
> Use DESTDIR and PREFIX instead of INSTALL_LOCATION

- .travis.yml
While working on #288 I found some ways to simplify the Travis configuration. The updated configuration has the same behavior as before, except that it now requires Xenial (which is the Travis default).
> Modernize Travis config

- .travis.yml
- CMakeLists.txt
- src/Makefile
- src/worksheet.c
Use `fmemopen` to create an in-memory `FILE *` for reading in image attributes. This avoids creating a separate temporary file for every image added to the worksheet.
Passing `NULL` as the first argument creates a buffer managed by `fmemopen`; I tried it the other way (passing in the buffer created elsewhere in `worksheet_insert_image_buffer_opt`) but it didn't seem to work. (Possibly a case of me misusing the API.)
According to the documentation, `fclose` will free the buffer, so I believe that this one line change is sufficient.
According to header comments on my platform (macOS 10.15) it looks like `fmemopen` is defined by POSIX.1-2008. We might need to wrap the feature in a #define to support older platforms. The change compiles, runs, and seems to work on macOS, but I haven't tested …
> Add image buffers without a temporary file

- CMakeLists.txt
- Makefile
- dev/release/pkg-config.txt
Fixes: https://github.com/jmcnamara/libxlsxwriter/issues/132
This PR adds pkg-config files to Makefile and CMake builds. I know that #132 was closed because the simplicity of linking libxlsxwriter doesn't require pkg-config. However, the reason I'm doing this is that I'm writing a Swift binding to libxlsxwriter and SwiftPM has native support for pkg-config which would make it simpler to build in macOS and Linux. Even though there are other workarounds to this problem, I find using pkg-config the most convenient solution.
> Add pkg-config files to the build

- src/Makefile
This Makefile builds 3 versions of each object: a regular one, one
usable for linking into a shared object, and one for tests, each with
different flags. They are named .o, .so, and .to respectively -- but
these .so files are regular object files, NOT shared libraries.
Hence, they shouldn't be built with ${LDFLAGS} because no linking is
happening here, they're just regular object files compiled with -c.
Passing on LDFLAGS here anyway can cause warnings or errors like this:
$ make V=1 LDFLAGS=-Wl,-rpath,/opt/pkg/lib
...
cc -fPIC -I../include -Wl,-rpath,/opt/pkg/lib -g -O3 -Wall -Wextra -Wstrict-prototypes -pedantic -ansi    -c app.c -o app.so
clang: warning: -Wl,-rpath,/opt/pkg/lib: 'linker' input unused [-Wunused-command-line-argument]
...
(Of course the actual linking into …
> Don't use LDLFAGS when building these .so files

- test/functional/src/Makefile
- test/unit/Makefile
- test/unit/Makefile.unit
Otherwise it's not possible to link e.g. system minizip if it's outside
the default search paths.
> Respect LDFLAGS when linking tests

- Makefile
- docs/Makefile
- examples/Makefile
- src/Makefile
- test/functional/src/Makefile
- test/unit/Makefile
- test/unit/Makefile.unit
- third_party/dtoa/Makefile
- third_party/md5/Makefile
- third_party/minizip/Makefile
- third_party/tmpfileplus/Makefile
Users and developers may have to make some `make` configuration changes
to suit the local environment, for example for setting up library search
paths. To avoid having to type arguments to `make` every time temporary local
changes may be made to Makefiles but this presents two problems:
1. There are many Makefiles used in this project that must be edited.
2. It clutters the git status and makes it easy to accidentally commit
such a local Makefile change.
This commit adds includes for an optional, top level `config.mk` for
local changes, ignored by version control.
> Support user-supplied config.mk

- test/cpp/Makefile
Setting USE_SYSTEM_MINIZIP and USE_OPENSSL_MD5 causes minizip and crypto
respectively to become dependencies of libxlsxwriter, hence then they
need to be linked in the C++ test, too.
> Link minizip and crypto in C++ test if required

- test/cpp/Makefile
E.g. so libraries are found when using a third-party package manager.
> Respect LDFLAGS in test/cpp/Makefile

- include/xlsxwriter/worksheet.h
- src/packager.c
- src/worksheet.c
macOS does not like rewinding and reading from a memstream (it messes up the buffer) which is fair enough - per spec, `open_memstream()` returns a write-only stream. This PR ensures the buffer is read from directly to avoid this.
> Improve buffer support

- Package.swift
- test/swift/test.swift
Fix #390
The test verifies that the library can be used from a Swift context. This was helpful to solve missing symbols as I chose which files I had to include. In the end, looking at the `.podspec` was very helpful.
> Add Swift Package Manager support

- Makefile
No need to configure the cache and threads anymore, SonarCloud now has automatic analysis caching and threads configuration. See: https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#analysis-cache
> Remove SonarCloud cache and threads configuration and rely on default

- CMakeLists.txt
Fix #398 
This PR is intended to fix the bug caused by find_package()
See https://cmake.org/cmake/help/latest/command/find_package.html
> Fix zlib/minizip dep required version in CMake

- .gitignore
- build.zig
- build.zig.zon
closes #401
* Download [Zig v0.11 or higher](https://ziglang.org/download)
* Make on your project `build.zig` & `build.zig.zon` file
e.g:
* **build.zig**
```zig
const libxlsxwriter_dep = b.dependency("libxlsxwriter", .{ // <== as declared in build.zig.zon
.target = target, // the same as passing `-Dtarget=<...>` to the library's build.zig script
.optimize = optimize, // ditto for `-Doptimize=<...>`
});
const libxlsxwriter = libxlsxwriter_dep.artifact("xlsxwriter"); // <== has the location of the dependency files (libxlsxwriter)
/// your executable config
exe.linkLibrary(libxlsxwriter); // <== link libxlsxwriter
exe.installLibraryHeaders(libxlsxwriter); // <== get copy libxlsxwriter headers to zig-out/include 
```
* **build.zig.zon**
```zig
.{
.name = "example",
.version = "0.1.0", …
```
> Zig package

- third_party/minizip/Makefile.orig
- third_party/minizip/MiniZip64_Changes.txt
- third_party/minizip/configure.ac
- third_party/minizip/crypt.h
- third_party/minizip/ioapi.c
- third_party/minizip/ioapi.h
- third_party/minizip/iowin32.c
- third_party/minizip/iowin32.h
- third_party/minizip/miniunz.c
- third_party/minizip/minizip.c
- third_party/minizip/mztools.c
- third_party/minizip/unzip.c
- third_party/minizip/unzip.h
- third_party/minizip/zip.c
- third_party/minizip/zip.h
Updates the vendored copy of `minizip` within `libxlsxwriter` to the version [distributed with version 1.3 of `zlib`](https://github.com/madler/zlib/tree/09155eaa2f9270dc4ed1fa13e2b4b2613e6e4851/contrib/minizip) with a few `libxlsxwriter` customizations retained / re-applied.
I have run the tests (`make test`) and valgrind checks (`make test_valgrind`) on a system where `minizip` is not available as a system-provided library (to make sure that the vendored copy of the code was in use) and these passed.
Abbreviated output from the tests is included below:
```
$ make test
...
RESULTS: 430 tests (430 ok, 0 failed, 0 skipped) ran in 40.4 ms
...
=============================================================== 759 passed in 8.08s =============================================================== …
```
> Maintenance: update vendored minizip code to the version distributed with zlib v1.3

- .github/workflows/zig_build.yml
- build.zig
> zig: Fix CI

- third_party/minizip/zip.c
With the `minizip` code in the codebase updated by #420, it's fairly straightforward to cherry-pick a fixup for CVE-2023-45853.
If-and-when a release of `zlib` v1.3.1 (that contains `minizip` in the `contrib` directory) appears, it could be worthwhile to update to that; since that hasn't appeared yet I think it may make sense to apply this here directly.
> From zlib: Reject overflows of zip header fields in minizip.

- .cirrus.yml
Apologies for not opening an issue first -- this is not a bug report or really a new feature, and to me it seems for this change an open issue wouldn't add much value. But I'm happy to do so, if that's important for your workflow / tracking.
This change adds FreeBSD build + test CI via [Cirrus-CI](https://cirrus-ci.org). For a sample run see https://cirrus-ci.com/build/5293314581200896
Enabling it requires adding the Cirrus-CI application, documented at https://cirrus-ci.org/guide/quick-start/.
> Add FreeBSD CI via Cirrus-CI

- include/xlsxwriter/third_party/ioapi.h
- include/xlsxwriter/third_party/zip.h
- third_party/minizip/Makefile.orig
- third_party/minizip/configure.ac
- third_party/minizip/ioapi.h
- third_party/minizip/miniunz.c
- third_party/minizip/unzip.c
- third_party/minizip/unzip.h
- third_party/minizip/zip.c
- third_party/minizip/zip.h
Updates the vendored copy of `minizip` within `libxlsxwriter` to the version [distributed with version 1.3.1 of zlib](https://github.com/madler/zlib/tree/51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf/contrib/minizip).
The diff here should match with the relevant changes between v1.3 and v1.3.1 of `zlib` ( https://github.com/madler/zlib/compare/v1.3...v1.3.1 ), with the exception of 1dfd55bf17434fb5b4530597343129acbda71806 that is a cherry-pick already applied locally (#427) from madler/zlib@73331a6a0481067628f065ffe87bb1d8f787d10c (an upstream fix).
Test results:
* `make test`
* unit tests: 430 passed, 0 failed, 0 skipped.
* functional tests: 759 passed, 0 failed, 0 skipped.
* `make test_valgrind`
* completed successfully with exit code zero.
(this is a follow-up to issue #419; I'd been …
> Maintenance: updated vendored minizip code to the version distributed with zlib v1.3.1

- .github/workflows/zig_build.yml
- build.zig
- build.zig.zon
**Release Notes:** https://ziglang.org/download/0.12.0/release-notes.html
Previously, `zlib` dependency also needed `build.zig` in the repository. However, this new version finds the root path of dependencies and doesn't need to add `build.zig` at all.
`zlib-src` is the upstream. Everything goes back to that build.zig ( from this project)!
cc: @jmcnamara
> Update zig-build to v0.12.0

- CMakeLists.txt
Try to find libraries using pkgconfig and fallback to old behaviour if that fails
> CMake: Check for third party libraries using pkgconfig

- .github/workflows/zig_build.yml
- .gitignore
- build.zig
- build.zig.zon
Minor fix: lazyPath
`b.path("path")` - get src/subpath contents - not allow abspath
old `.{ .path = "path" }` was renamed to `.{ .cwd_relative = "abspath" }` - for external path.
Works on zig version: v0.12.0 (optional change), v0.12.1, v0.13.0 & v0.14.0-dev (currently master);
**Note:** old zig version generate `zig-cache`, but v013.0 and master rename to `.zig-cache`!
Extra update: replacing zlib-master to release-version
```bash
$ zig fetch --save=zlib git+https://github.com/madler/zlib#v1.3.1
info: resolved ref 'v1.3.1' to commit 51b7f2abdade71cd9bb0e7a373ef2610ec6f9daf
warning: overwriting existing dependency named 'zlib'
```
cc: @jmcnamara
> zig-build: lazyPath fixes

- build.zig
Small change to build.zig due to change in the zig build system, in the way it passes C Macros from the Zig build system to the target 
defineCMacro() -> deprecated in favour of -> root_lib.addCMacro()
Recently deprecated & removed from the zig compiler 
https://github.com/ziglang/zig/commit/142471fcc46070326526e3976f0150fe734df0b6
This change has no effect on libxlswriter itself - its a zig issue, no a libxlswriter issue
Tested - built using a patched zig-libxlswriter, and added to my app for end 2 end test to generate spreadsheets.
> #465 change from defineCMacro to addCMacro

- build.zig.zon
@kassane  - for review please
All patches and pull requests are welcome but in general you should start with
an issue tracker to describe what you intend to do before you do it.
1. Pull requests and new feature proposals must start with an [issue
tracker][issues]. This serves as the focal point for the design discussion.
2. Describe what you plan to do. If there are API changes add some code
example to demonstrate them.
3. Fork the repository.
4. Run all the tests to make sure the current code works on your system using
`make test`.  See the [Running the Test Suite][tests] section of the docs
for instructions.
5. Create a feature branch for your new feature.
[tests]: http://libxlsxwriter.github.io/running_the_tests.html
The code style is mainly K&R style with 4 space indents.
The author …
> update for zig build tools #474
